---
title: "Gov 50 Final Project"
author: "Joseph Alexander"
description: "My final project"
output:
  distill::distill_article: 
    self_contained: false
---

  

## Proposal (to be changed)

My data set is from the following study: Stefano DellaVigna and Ethan Kaplan 2007. "The Fox News Effect: Media Bias and Voting." 1) Can partisan messages in the news media impact voter choice in elections? 2) I hypothesize that towns with greater levels of subscription to Fox News in 2000 will vote GOP more strongly in the 2000 presidential election. 3) One explanatory variable could be Share of Fox News subscribers in 2000. 4) An outcome variable of interest would be Two-party vote share for the Republicans (2000 Presidential election) 5) If higher shares of Fox News subscribers are associated with higher share of support for the GOP in election 2000, my hypothesis is supported. If higher shares of Fox News subscribers are not associated with higher share of support for the GOP in election 2000, my hypothesis is undermined.


```{r}


# Visualization #1 (GOP Vote Share 2000)
foxnews$V9 <- as.numeric(foxnews$V9)
foxnews$V12 <- as.numeric(foxnews$V12)

ggplot(data = foxnews, aes(x = V9, y = V12)) + geom_point() + geom_smooth() +
  labs(x = "Share of Town Subscribed to Fox News in 2000", y = "Share of Town which voted GOP in 2000",
       title = "Fox News and GOP Vote Share in 2000",
       subtitle = "",
       caption = "Data from 2000") + theme(
    axis.title.x = element_text(size = 8),
    axis.title.y = element_text(size = 8)
  )
```

